apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autodev-staging
resources: [../../base]
images:
  - name: api
    newName: REPLACE_ECR_REGISTRY/autodev-api
    digest: sha256:REPLACE_API_DIGEST
  - name: web
    newName: REPLACE_ECR_REGISTRY/autodev-web
    digest: sha256:REPLACE_WEB_DIGEST
