apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: api-runtime
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "REPLACE_API_SECRET_NAME"
        objectType: "secretsmanager"
        jmesPath:
          - path: "DATABASE_URL"
            objectAlias: "DATABASE_URL"
  secretObjects:
    - secretName: api-runtime
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
